server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://10.190.56.7:3306/cdfwxmalldb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: nihao123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#spring:
#  datasource:
#    url: jdbc:oracle:thin:@10.190.3.10:1521:hncdfmkt001
#    username: dbusrmkt
#    password: nibuhao123456!
#    driver-class-name: oracle.jdbc.OracleDriver
#    type: com.alibaba.druid.pool.DruidDataSource
